// See https://aka.ms/new-console-template for more information

using GenericList.Classes;

Console.WriteLine("Generic List Starting");

List<EmployeeClass> employees = new List<EmployeeClass>();
List<CustomerClass> customers = new List<CustomerClass>();
List<PersonClass> persons = new List<PersonClass>();

// Names are a generated by ChatGPT

// make 3 employees
EmployeeClass e1 = new EmployeeClass("Anna", "van der", "Meer");
employees.Add(e1);

EmployeeClass e2 = new EmployeeClass("Joris", "de", "Vries");
employees.Add(e2);

EmployeeClass e3 = new EmployeeClass("Sophie", "ten", "Broeke");
employees.Add(e3);



// make 3 customers
CustomerClass c1 = new CustomerClass("Lucas", "van den", "Berg");
customers.Add(c1);

CustomerClass c2 = new CustomerClass("Mila", "ter", "Horst");
customers.Add(c2);

CustomerClass c3 = new CustomerClass("Thomas", "van", "Dijk");
customers.Add(c3);

Console.WriteLine("Employee List");
foreach (EmployeeClass e in employees)
{
    Console.WriteLine(e.VolledigeNaam());
    persons.Add(e);
}


Console.WriteLine("---------------------------------");
Console.WriteLine("Customer List");
foreach (CustomerClass c in customers)
{
    Console.WriteLine(c.VolledigeNaam());
    persons.Add(c);
}

Console.WriteLine("---------------------------------");
Console.WriteLine("Persons List");
foreach (PersonClass p in persons)
{
    Console.WriteLine(p.VolledigeNaam());
}

